export type Property = {
  id: number;
  address: string;
  suburb: string;
  type: "House" | "Townhouse" | "Unit" | "Apartment";
  price: number | null;
  priceMin?: number;
  priceMax?: number;
  priceStatus: "verified" | "estimated";
  rent: number;
  rentStatus: "verified" | "estimated";
  capitalGrowth: number;
  capitalGrowthStatus: "verified" | "estimated";
  beds: number;
  baths: number;
  cars: number;
  landSize?: number;
  source: "realestate.com.au" | "Domain";
  listingUrl?: string;
};

/*
 * IMPORTANT
 *
 * price/rent/growth are deliberately separated into:
 *   verified
 *   estimated
 *
 * This prevents the app from presenting an estimate as factual.
 *
 * The current dataset contains genuine listings identified from
 * current Canberra REA search inventory. Where the listing did not
 * publish a price or rent, the app estimates it and labels it.
 */

export const properties: Property[] = [
  {
    id: 1,
    address: "8 Tryon Street, Hackett",
    suburb: "Hackett",
    type: "House",
    price: null,
    priceStatus: "estimated",
    rent: 850,
    rentStatus: "estimated",
    capitalGrowth: 4.1,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 2,
    cars: 2,
    landSize: 716,
    source: "realestate.com.au",
  },
  {
    id: 2,
    address: "14 Ah Ket Rise, Denman Prospect",
    suburb: "Denman Prospect",
    type: "House",
    price: null,
    priceStatus: "estimated",
    rent: 850,
    rentStatus: "estimated",
    capitalGrowth: 4.8,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 3,
    cars: 2,
    landSize: 525,
    source: "realestate.com.au",
  },
  {
    id: 3,
    address: "1/131 Britten Jones Drive, Holt",
    suburb: "Holt",
    type: "House",
    price: 720000,
    priceStatus: "verified",
    rent: 650,
    rentStatus: "estimated",
    capitalGrowth: 3.8,
    capitalGrowthStatus: "estimated",
    beds: 3,
    baths: 2,
    cars: 2,
    landSize: 146,
    source: "realestate.com.au",
  },
  {
    id: 4,
    address: "3 Scott Street, Narrabundah",
    suburb: "Narrabundah",
    type: "House",
    price: 2100000,
    priceStatus: "estimated",
    rent: 1050,
    rentStatus: "estimated",
    capitalGrowth: 4.0,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 2,
    cars: 2,
    source: "realestate.com.au",
  },
  {
    id: 5,
    address: "32 Dengate Crescent, Moncrieff",
    suburb: "Moncrieff",
    type: "House",
    price: 950000,
    priceStatus: "estimated",
    rent: 720,
    rentStatus: "estimated",
    capitalGrowth: 4.5,
    capitalGrowthStatus: "estimated",
    beds: 5,
    baths: 3,
    cars: 2,
    landSize: 504,
    source: "realestate.com.au",
  },
  {
    id: 6,
    address: "10 Jenolan Street, Harrison",
    suburb: "Harrison",
    type: "House",
    price: 1050000,
    priceStatus: "estimated",
    rent: 780,
    rentStatus: "estimated",
    capitalGrowth: 4.3,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 3,
    cars: 2,
    landSize: 331,
    source: "realestate.com.au",
  },
  {
    id: 7,
    address: "B/2 Meymott Place, Latham",
    suburb: "Latham",
    type: "House",
    price: 1195000,
    priceStatus: "verified",
    rent: 800,
    rentStatus: "estimated",
    capitalGrowth: 3.9,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 2,
    cars: 2,
    landSize: 504,
    source: "realestate.com.au",
  },
  {
    id: 8,
    address: "1/23 Wrenfordsley Place, Latham",
    suburb: "Latham",
    type: "House",
    price: 720000,
    priceStatus: "verified",
    rent: 650,
    rentStatus: "estimated",
    capitalGrowth: 3.9,
    capitalGrowthStatus: "estimated",
    beds: 2,
    baths: 1,
    cars: 1,
    source: "realestate.com.au",
  },
  {
    id: 9,
    address: "70 Tallara Parkway, Narrabundah",
    suburb: "Narrabundah",
    type: "House",
    price: 2100000,
    priceStatus: "estimated",
    rent: 1100,
    rentStatus: "estimated",
    capitalGrowth: 4.0,
    capitalGrowthStatus: "estimated",
    beds: 6,
    baths: 4,
    cars: 2,
    landSize: 1032,
    source: "realestate.com.au",
  },
  {
    id: 10,
    address: "3 Juad Place, Aranda",
    suburb: "Aranda",
    type: "House",
    price: 1500000,
    priceStatus: "estimated",
    rent: 850,
    rentStatus: "estimated",
    capitalGrowth: 4.2,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 2,
    cars: 1,
    landSize: 776,
    source: "realestate.com.au",
  },
  {
    id: 11,
    address: "43 McLachlan Crescent, Weetangera",
    suburb: "Weetangera",
    type: "House",
    price: 1500000,
    priceStatus: "estimated",
    rent: 950,
    rentStatus: "estimated",
    capitalGrowth: 4.2,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 3,
    cars: 3,
    landSize: 1964,
    source: "realestate.com.au",
  },
  {
    id: 12,
    address: "5 Packer Street, Weetangera",
    suburb: "Weetangera",
    type: "House",
    price: 1250000,
    priceStatus: "estimated",
    rent: 800,
    rentStatus: "estimated",
    capitalGrowth: 4.2,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 2,
    cars: 2,
    landSize: 940,
    source: "realestate.com.au",
  },
  {
    id: 13,
    address: "6 Cloncurry Street, Kaleen",
    suburb: "Kaleen",
    type: "House",
    price: 875000,
    priceStatus: "verified",
    rent: 720,
    rentStatus: "estimated",
    capitalGrowth: 4.0,
    capitalGrowthStatus: "estimated",
    beds: 3,
    baths: 2,
    cars: 2,
    source: "realestate.com.au",
  },
  {
    id: 14,
    address: "2 Parkhill Street, Pearce",
    suburb: "Pearce",
    type: "House",
    price: 1300000,
    priceStatus: "estimated",
    rent: 800,
    rentStatus: "estimated",
    capitalGrowth: 4.4,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 2,
    cars: 3,
    landSize: 1132,
    source: "realestate.com.au",
  },
  {
    id: 15,
    address: "5A Marshall Street, Farrer",
    suburb: "Farrer",
    type: "House",
    price: 750000,
    priceStatus: "estimated",
    rent: 600,
    rentStatus: "estimated",
    capitalGrowth: 4.4,
    capitalGrowthStatus: "estimated",
    beds: 2,
    baths: 1,
    cars: 1,
    landSize: 93,
    source: "realestate.com.au",
  },
  {
    id: 16,
    address: "294 Goyder Street, Narrabundah",
    suburb: "Narrabundah",
    type: "House",
    price: 1150000,
    priceStatus: "estimated",
    rent: 720,
    rentStatus: "estimated",
    capitalGrowth: 4.0,
    capitalGrowthStatus: "estimated",
    beds: 3,
    baths: 1,
    cars: 1,
    landSize: 714,
    source: "realestate.com.au",
  },
  {
    id: 17,
    address: "99 Hibberd Crescent, Forde",
    suburb: "Forde",
    type: "House",
    price: 1049000,
    priceStatus: "verified",
    rent: 760,
    rentStatus: "estimated",
    capitalGrowth: 4.5,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 2,
    cars: 2,
    source: "realestate.com.au",
  },
  {
    id: 18,
    address: "10 Helmrich Street, Moncrieff",
    suburb: "Moncrieff",
    type: "House",
    price: 1100000,
    priceStatus: "verified",
    rent: 780,
    rentStatus: "estimated",
    capitalGrowth: 4.5,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 2,
    cars: 2,
    landSize: 468,
    source: "realestate.com.au",
  },
  {
    id: 19,
    address: "18 Carmody Street, Casey",
    suburb: "Casey",
    type: "House",
    price: 1039000,
    priceStatus: "verified",
    rent: 760,
    rentStatus: "estimated",
    capitalGrowth: 4.4,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 2,
    cars: 2,
    landSize: 447,
    source: "realestate.com.au",
  },
  {
    id: 20,
    address: "43 Throssell Street, Curtin",
    suburb: "Curtin",
    type: "House",
    price: 1500000,
    priceStatus: "verified",
    rent: 850,
    rentStatus: "estimated",
    capitalGrowth: 4.5,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 2,
    cars: 2,
    source: "realestate.com.au",
  },
  {
    id: 21,
    address: "77 Franklin Street, Forrest",
    suburb: "Forrest",
    type: "House",
    price: 3250000,
    priceStatus: "estimated",
    rent: 1300,
    rentStatus: "estimated",
    capitalGrowth: 4.1,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 2,
    cars: 6,
    source: "realestate.com.au",
  },
  {
    id: 22,
    address: "75 Franklin Street, Forrest",
    suburb: "Forrest",
    type: "House",
    price: 3250000,
    priceStatus: "estimated",
    rent: 1300,
    rentStatus: "estimated",
    capitalGrowth: 4.1,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 2,
    cars: 6,
    source: "realestate.com.au",
  },
  {
    id: 23,
    address: "4 Alison Ashby Crescent, Banks",
    suburb: "Banks",
    type: "House",
    price: 1095000,
    priceStatus: "verified",
    rent: 750,
    rentStatus: "estimated",
    capitalGrowth: 4.2,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 2,
    cars: 2,
    landSize: 640,
    source: "realestate.com.au",
  },
  {
    id: 24,
    address: "50 Candlebark Close, Nicholls",
    suburb: "Nicholls",
    type: "House",
    price: 1040000,
    priceStatus: "verified",
    rent: 750,
    rentStatus: "estimated",
    capitalGrowth: 4.2,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 2,
    cars: 2,
    landSize: 434,
    source: "realestate.com.au",
  },
  {
    id: 25,
    address: "10/147 Bill Ferguson Circuit, Bonner",
    suburb: "Bonner",
    type: "Townhouse",
    price: 730000,
    priceStatus: "verified",
    rent: 650,
    rentStatus: "estimated",
    capitalGrowth: 4.5,
    capitalGrowthStatus: "estimated",
    beds: 3,
    baths: 2,
    cars: 2,
    landSize: 152,
    source: "realestate.com.au",
  },
  {
    id: 26,
    address: "12/8 Berrigan Crescent, O'Connor",
    suburb: "O'Connor",
    type: "Townhouse",
    price: 1130000,
    priceStatus: "verified",
    rent: 750,
    rentStatus: "estimated",
    capitalGrowth: 4.3,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 4,
    cars: 2,
    source: "realestate.com.au",
  },
  {
    id: 27,
    address: "19/8 Henry Kendall Street, Franklin",
    suburb: "Franklin",
    type: "Townhouse",
    price: 525000,
    priceStatus: "verified",
    rent: 550,
    rentStatus: "estimated",
    capitalGrowth: 4.6,
    capitalGrowthStatus: "estimated",
    beds: 2,
    baths: 1,
    cars: 1,
    landSize: 70,
    source: "realestate.com.au",
  },
  {
    id: 28,
    address: "10 Bob Whan Street, Strathnairn",
    suburb: "Strathnairn",
    type: "Townhouse",
    price: 849000,
    priceStatus: "verified",
    rent: 680,
    rentStatus: "estimated",
    capitalGrowth: 4.8,
    capitalGrowthStatus: "estimated",
    beds: 3,
    baths: 2,
    cars: 2,
    source: "realestate.com.au",
  },
  {
    id: 29,
    address: "89/235 Flemington Road, Franklin",
    suburb: "Franklin",
    type: "Townhouse",
    price: 650000,
    priceStatus: "estimated",
    rent: 570,
    rentStatus: "estimated",
    capitalGrowth: 4.4,
    capitalGrowthStatus: "estimated",
    beds: 3,
    baths: 2,
    cars: 2,
    source: "realestate.com.au",
  },
  {
    id: 30,
    address: "8/4 Lind Close, Fraser",
    suburb: "Fraser",
    type: "Townhouse",
    price: 780000,
    priceStatus: "verified",
    rent: 650,
    rentStatus: "estimated",
    capitalGrowth: 4.1,
    capitalGrowthStatus: "estimated",
    beds: 3,
    baths: 2,
    cars: 2,
    landSize: 141,
    source: "realestate.com.au",
  },
  {
    id: 31,
    address: "5/21 Temperley Street, Nicholls",
    suburb: "Nicholls",
    type: "Townhouse",
    price: 850000,
    priceStatus: "estimated",
    rent: 690,
    rentStatus: "estimated",
    capitalGrowth: 4.3,
    capitalGrowthStatus: "estimated",
    beds: 3,
    baths: 2,
    cars: 2,
    landSize: 165,
    source: "realestate.com.au",
  },
  {
    id: 32,
    address: "5/45 Stockdale Street, Dickson",
    suburb: "Dickson",
    type: "Townhouse",
    price: 800000,
    priceStatus: "estimated",
    rent: 650,
    rentStatus: "estimated",
    capitalGrowth: 4.2,
    capitalGrowthStatus: "estimated",
    beds: 2,
    baths: 2,
    cars: 2,
    landSize: 127,
    source: "realestate.com.au",
  },
  {
    id: 33,
    address: "43/2 Pipeclay Street, Lawson",
    suburb: "Lawson",
    type: "Townhouse",
    price: 780000,
    priceStatus: "verified",
    rent: 640,
    rentStatus: "estimated",
    capitalGrowth: 4.5,
    capitalGrowthStatus: "estimated",
    beds: 3,
    baths: 2,
    cars: 2,
    source: "realestate.com.au",
  },
  {
    id: 34,
    address: "8/15 Oxenham Street, Gordon",
    suburb: "Gordon",
    type: "Townhouse",
    price: 750000,
    priceStatus: "estimated",
    rent: 630,
    rentStatus: "estimated",
    capitalGrowth: 4.0,
    capitalGrowthStatus: "estimated",
    beds: 3,
    baths: 2,
    cars: 2,
    landSize: 133,
    source: "realestate.com.au",
  },
  {
    id: 35,
    address: "16/31 Moyes Crescent, Holt",
    suburb: "Holt",
    type: "Townhouse",
    price: 590000,
    priceStatus: "verified",
    rent: 530,
    rentStatus: "estimated",
    capitalGrowth: 3.9,
    capitalGrowthStatus: "estimated",
    beds: 2,
    baths: 1,
    cars: 1,
    landSize: 82,
    source: "realestate.com.au",
  },
  {
    id: 36,
    address: "38/60 Copland Drive, Evatt",
    suburb: "Evatt",
    type: "Townhouse",
    price: 639000,
    priceStatus: "verified",
    rent: 560,
    rentStatus: "estimated",
    capitalGrowth: 4.0,
    capitalGrowthStatus: "estimated",
    beds: 2,
    baths: 2,
    cars: 2,
    source: "realestate.com.au",
  },
  {
    id: 37,
    address: "21 Grenfell Avenue, Taylor",
    suburb: "Taylor",
    type: "Townhouse",
    price: 650000,
    priceStatus: "estimated",
    rent: 600,
    rentStatus: "estimated",
    capitalGrowth: 4.8,
    capitalGrowthStatus: "estimated",
    beds: 3,
    baths: 2,
    cars: 2,
    landSize: 111,
    source: "realestate.com.au",
  },
  {
    id: 38,
    address: "15/1 Flecker Place, Florey",
    suburb: "Florey",
    type: "Townhouse",
    price: 640000,
    priceStatus: "verified",
    rent: 560,
    rentStatus: "estimated",
    capitalGrowth: 4.1,
    capitalGrowthStatus: "estimated",
    beds: 2,
    baths: 1,
    cars: 2,
    source: "realestate.com.au",
  },
  {
    id: 39,
    address: "6/91 Ainsworth Street, Mawson",
    suburb: "Mawson",
    type: "Townhouse",
    price: 1275000,
    priceStatus: "estimated",
    rent: 750,
    rentStatus: "estimated",
    capitalGrowth: 4.3,
    capitalGrowthStatus: "estimated",
    beds: 3,
    baths: 2,
    cars: 2,
    source: "realestate.com.au",
  },
  {
    id: 40,
    address: "7/1 Moulder Court, Charnwood",
    suburb: "Charnwood",
    type: "Townhouse",
    price: 450000,
    priceStatus: "verified",
    rent: 430,
    rentStatus: "estimated",
    capitalGrowth: 3.8,
    capitalGrowthStatus: "estimated",
    beds: 1,
    baths: 1,
    cars: 1,
    source: "realestate.com.au",
  },
  {
    id: 41,
    address: "5/86 Mawson Drive, Mawson",
    suburb: "Mawson",
    type: "Townhouse",
    price: 659000,
    priceStatus: "verified",
    rent: 570,
    rentStatus: "estimated",
    capitalGrowth: 4.2,
    capitalGrowthStatus: "estimated",
    beds: 2,
    baths: 1,
    cars: 1,
    landSize: 77,
    source: "realestate.com.au",
  },
  {
    id: 42,
    address: "9/148 Overall Avenue, Casey",
    suburb: "Casey",
    type: "Townhouse",
    price: 740000,
    priceStatus: "estimated",
    rent: 650,
    rentStatus: "estimated",
    capitalGrowth: 4.5,
    capitalGrowthStatus: "estimated",
    beds: 3,
    baths: 3,
    cars: 2,
    source: "realestate.com.au",
  },
  {
    id: 43,
    address: "4/21 Bernard Heinze Avenue, Moncrieff",
    suburb: "Moncrieff",
    type: "Townhouse",
    price: 595000,
    priceStatus: "verified",
    rent: 550,
    rentStatus: "estimated",
    capitalGrowth: 4.5,
    capitalGrowthStatus: "estimated",
    beds: 2,
    baths: 2,
    cars: 1,
    landSize: 101,
    source: "realestate.com.au",
  },
  {
    id: 44,
    address: "37/14 Federal Highway, Watson",
    suburb: "Watson",
    type: "Townhouse",
    price: 680000,
    priceStatus: "verified",
    rent: 580,
    rentStatus: "estimated",
    capitalGrowth: 4.1,
    capitalGrowthStatus: "estimated",
    beds: 2,
    baths: 2,
    cars: 1,
    source: "realestate.com.au",
  },
  {
    id: 45,
    address: "19/11 Starcevich Crescent, Jacka",
    suburb: "Jacka",
    type: "Townhouse",
    price: 700000,
    priceStatus: "estimated",
    rent: 620,
    rentStatus: "estimated",
    capitalGrowth: 4.7,
    capitalGrowthStatus: "estimated",
    beds: 2,
    baths: 2,
    cars: 2,
    landSize: 93,
    source: "realestate.com.au",
  },
  {
    id: 46,
    address: "230 Robin Boyd Crescent, Taylor",
    suburb: "Taylor",
    type: "Townhouse",
    price: 835000,
    priceStatus: "estimated",
    rent: 680,
    rentStatus: "estimated",
    capitalGrowth: 4.8,
    capitalGrowthStatus: "estimated",
    beds: 3,
    baths: 2,
    cars: 2,
    source: "realestate.com.au",
  },
  {
    id: 47,
    address: "42 Smeaton Circuit, Banks",
    suburb: "Banks",
    type: "House",
    price: 900000,
    priceStatus: "estimated",
    rent: 700,
    rentStatus: "estimated",
    capitalGrowth: 4.1,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 2,
    cars: 2,
    source: "realestate.com.au",
  },
  {
    id: 48,
    address: "24/10 Trevillian Quay, Kingston",
    suburb: "Kingston",
    type: "Apartment",
    price: 750000,
    priceStatus: "estimated",
    rent: 650,
    rentStatus: "estimated",
    capitalGrowth: 3.8,
    capitalGrowthStatus: "estimated",
    beds: 2,
    baths: 2,
    cars: 1,
    source: "realestate.com.au",
  },
  {
    id: 49,
    address: "75 Sullivan Crescent, Wanniassa",
    suburb: "Wanniassa",
    type: "House",
    price: 850000,
    priceStatus: "estimated",
    rent: 680,
    rentStatus: "estimated",
    capitalGrowth: 3.9,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 2,
    cars: 2,
    source: "realestate.com.au",
  },
  {
    id: 50,
    address: "3 Curlewis Crescent, Garran",
    suburb: "Garran",
    type: "House",
    price: 1300000,
    priceStatus: "estimated",
    rent: 800,
    rentStatus: "estimated",
    capitalGrowth: 4.2,
    capitalGrowthStatus: "estimated",
    beds: 4,
    baths: 2,
    cars: 2,
    source: "realestate.com.au",
  },
];

/*
 * This is intentionally an array rather than a hard-coded limit.
 *
 * When we connect the legitimate listing feed/API, simply append
 * additional Property records here. The UI does not need changing.
 */